### ISSUE TITLE
Error: cannot import name 'LlamaForCausalLM' from 'optimum.nvidia' 

### ISSUE THREAD

**Issue by taozhang9527** [huggingface/optimum-nvidia#23]
I am trying to run [the example generate code provided](https://github.com/huggingface/optimum-nvidia#generate) with the docker image version 0.1.0b1. It gives me the following error:
`    from optimum.nvidia import LlamaForCausalLM
ImportError: cannot import name 'LlamaForCausalLM' from 'optimum.nvidia' (/opt/optimum-nvidia/src/optimum/nvidia/__init__.py)
`
How to address this?

**Comment by laikhtewari** [comment]
Try running `from optimum.nvidia import AutoModelForCausalLM` instead

Thanks for catching this!

**Comment by taozhang9527** [comment]
It works. fp8 quantization takes a long time. How to enable the distributed/parallel inference to different GPUs? With the sample code, 
`torch.distributed not initialized, assuming single world_size.
`  
How's the performance compared to tensorRT and TensorRT-LLM? It looks to me that optimum is built on top of TensorRT, we are supposed to get similar performance, right?

**Comment by mfuntowicz** [comment]
It's now fixed in the last release `0.1.0b2`

Thanks for raising this 🤗
