### ISSUE TITLE
fatal: Fetched in submodule path 'third-party/tensorrt-llm', but it did not contain 37aa4499520eea1d6c6dbc04a66d77bef00014f5. Direct fetching of that commit failed.

### ISSUE THREAD

**Issue by hellostronger** [huggingface/optimum-nvidia#86]
our optinum-nvidia reposity  link to another reposity   is  invalid  which in the path third-party/tensorrt-llm ,is it a problem? how to fix it???

**Comment by erickchandra1** [comment]
Go to the `third-party` directory, pull the latest TensorRT-LLM from the official repository [https://github.com/NVIDIA/TensorRT-LLM/tree/gemma](https://github.com/NVIDIA/TensorRT-LLM/tree/gemma), and then `git checkout 3c373eb`.

Proceed with the remaining commands:
```
make -C docker release_build CUDA_ARCHS=$TARGET_SM
cd ../.. && docker build -t <organisation_name/image_name>:<version> -f docker/Dockerfile .
```

Tested and worked on my case.

**Comment by erickchandra1** [comment]
Go to the `third-party` directory, clone and pull the latest TensorRT-LLM from the official repository [https://github.com/NVIDIA/TensorRT-LLM](https://github.com/NVIDIA/TensorRT-LLM), and then `git checkout 3c373eb`.

Proceed with the remaining commands:
```
make -C docker release_build CUDA_ARCHS=$TARGET_SM
cd ../.. && docker build -t <organisation_name/image_name>:<version> -f docker/Dockerfile .
```

Tested and worked on my case.

**Comment by mfuntowicz** [comment]
Thanks for reporting @hellostronger - the issue has been fixed ✅
